### ISSUE TITLE
Not working on Camunda Modeler 4.2.0

### ISSUE THREAD

**Issue by Ichigo85** [sharedchains/camunda-modeler-plugin-multidiagram#5]
An user (Antonio_Junior) on Camunda Modeler Forum wrote that he is receiving this error message after copying the plugin.

`[diagram_1.bpmn] Cannot read property ‘getFormsTab’ of undefined
at GeneratedFormPreviewPluginProvider.getTabs (webpack:///client/GeneratedFormPreviewPluginProvider.js:22:0)
at GeneratedFormPreviewPluginProvider.CallActivityExt.propertiesProvider.getTabs (webpack:///client/properties-provider/CallActivityExt.js:71:0)
at getTabs (webpack:///node_modules/bpmn-js-properties-panel/lib/PropertiesPanel.js:446:41)
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:97811
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/2.2.js:1:45005
at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:365:33)
at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:350:23)
at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:311:23)
at fire (webpack:///node_modules/diagram-js/lib/core/Canvas.js:477:13)
at setRootElement (webpack:///node_modules/bpmn-js/lib/import/BpmnImporter.js:112:17)
at add (webpack:///node_modules/bpmn-js/lib/import/Importer.js:53:24)
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:29935
at rootElement (webpack:///node_modules/bpmn-js/lib/import/BpmnTreeWalker.js:215:24)
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:356935
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:356958
at new Promise ()
at F (webpack:///node_modules/bpmn-js/lib/import/Importer.js:72:9)
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:362018
at new Promise ()
at A. (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:286:9)
at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:361502
at new Promise ()
at A. (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:228:9)
at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:360771 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
[diagram_1.bpmn] Cannot read property ‘id’ of undefined
at file:///D:/Camunda/Modeler%204.2/resources/plugins/camunda-modeler-plugin-multidiagram/client/client.js:514:93
at file:///D:/Camunda/Modeler%204.2/resources/plugins/camunda-modeler-plugin-multidiagram/client/client.js:28190:9
at forEach (webpack:///node_modules/min-dash/dist/index.esm.js:145:0)
at find (webpack:///node_modules/min-dash/dist/index.esm.js:77:0)
at DiagramUtil…/client/bpmn-js-extension/multi-diagram/utils/DiagramUtil.js.DiagramUtil.currentDiagram (webpack:///client/bpmn-js-extension/multi-diagram/utils/DiagramUtil.js:23:0)
at file:///D:/Camunda/Modeler%204.2/resources/plugins/camunda-modeler-plugin-multidiagram/client/client.js:993:38
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/2.2.js:1:45005
at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:365:33)
at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:350:23)
at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:311:23)
at fire (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:662:30)
at file:///D:/Camunda/Modeler%204.2/resources/app.asar/public/5.5.js:1:360981 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]`

**Comment by Ichigo85** [comment]
There is an issue on [Camunda UserTask Generated Form Preview](https://github.com/camunda-consulting/code/tree/master/snippets/camunda-modeler-plugins/camunda-modeler-plugin-usertask-generatedform-preview) plugin, which cannot work with multiple propertiesProvider.
